import { bigint, boolean, index, integer, jsonb, pgSchema, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import { shareToken, uuidv7 } from './ids.ts';

/**
 * Every ReKod table lives in the `rekod` Postgres schema, not `public`: on
 * Supabase, `public` is served to the publishable key by the Data API, and
 * with no RLS a table there would be world-readable.
 */
export const rekod = pgSchema('rekod');

// ── Better Auth (core + organization plugin) ────────────────────────────────
// Generated by `npx @better-auth/cli generate`, moved into the rekod schema.
// Regenerate and diff when adding a Better Auth plugin; do not hand-edit fields.

export const user = rekod.table('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').default(false).notNull(),
  image: text('image'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().$onUpdate(() => new Date()).notNull(),
});

export const session = rekod.table('session', {
  id: text('id').primaryKey(),
  expiresAt: timestamp('expires_at').notNull(),
  token: text('token').notNull().unique(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').$onUpdate(() => new Date()).notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  activeOrganizationId: text('active_organization_id'),
}, (t) => [index('session_user_id_idx').on(t.userId)]);

export const account = rekod.table('account', {
  id: text('id').primaryKey(),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: timestamp('access_token_expires_at'),
  refreshTokenExpiresAt: timestamp('refresh_token_expires_at'),
  scope: text('scope'),
  password: text('password'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').$onUpdate(() => new Date()).notNull(),
}, (t) => [index('account_user_id_idx').on(t.userId)]);

export const verification = rekod.table('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: timestamp('expires_at').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().$onUpdate(() => new Date()).notNull(),
}, (t) => [index('verification_identifier_idx').on(t.identifier)]);

/** A workspace. Better Auth calls it an organization; the UI never does. */
export const organization = rekod.table('organization', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  logo: text('logo'),
  createdAt: timestamp('created_at').notNull(),
  metadata: text('metadata'),
});

export const member = rekod.table('member', {
  id: text('id').primaryKey(),
  organizationId: text('organization_id').notNull().references(() => organization.id, { onDelete: 'cascade' }),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  role: text('role').default('member').notNull(),
  createdAt: timestamp('created_at').notNull(),
}, (t) => [
  index('member_organization_id_idx').on(t.organizationId),
  index('member_user_id_idx').on(t.userId),
]);

export const invitation = rekod.table('invitation', {
  id: text('id').primaryKey(),
  organizationId: text('organization_id').notNull().references(() => organization.id, { onDelete: 'cascade' }),
  email: text('email').notNull(),
  role: text('role'),
  status: text('status').default('pending').notNull(),
  expiresAt: timestamp('expires_at').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  inviterId: text('inviter_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
}, (t) => [
  index('invitation_organization_id_idx').on(t.organizationId),
  index('invitation_email_idx').on(t.email),
]);

// ── ReKod ───────────────────────────────────────────────────────────────────
// Every tenant table carries workspace_id, and src/lib/server filters on it in
// every query. That filter is the whole tenant boundary — there is no RLS.

const stamps = {
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().$onUpdate(() => new Date()).notNull(),
};

export const reports = rekod.table('reports', {
  id: uuid('id').primaryKey().$defaultFn(() => uuidv7()),
  workspaceId: text('workspace_id').notNull().references(() => organization.id, { onDelete: 'cascade' }),
  createdBy: text('created_by').references(() => user.id, { onDelete: 'set null' }),
  // Both compose inputs are optional, so an untitled report is '' — not null.
  title: text('title').notNull().default(''),
  description: text('description'),
  type: text('type', { enum: ['video', 'screenshot'] }).notNull(),
  pageUrl: text('page_url'),
  project: text('project'),                          // the page's host
  // Epoch ms, NOT a timestamp: the origin for (entry.t - t0) against the epoch
  // values inside the logs. created_at is the human-readable one.
  t0: bigint('t0', { mode: 'number' }).notNull(),
  durationMs: integer('duration_ms'),
  env: jsonb('env').$type<Record<string, unknown>>().notNull().default({}),
  // Upload state, not triage: processing until /complete sees the files.
  status: text('status', { enum: ['processing', 'ready', 'failed'] }).notNull().default('processing'),
  // Plain, not hashed: the owner copies the same link whenever they like.
  // 32 random bytes, so it is unguessable; unique so lookup is one index probe.
  shareToken: text('share_token').unique().$defaultFn(shareToken),
  ...stamps,
}, (t) => [
  index('reports_workspace_created_idx').on(t.workspaceId, t.createdAt.desc()),
]);

export const reportAssets = rekod.table('report_assets', {
  id: uuid('id').primaryKey().$defaultFn(() => uuidv7()),
  reportId: uuid('report_id').notNull().references(() => reports.id, { onDelete: 'cascade' }),
  workspaceId: text('workspace_id').notNull().references(() => organization.id, { onDelete: 'cascade' }),
  kind: text('kind', { enum: ['video', 'screenshot', 'logs', 'network'] }).notNull(),
  storageKey: text('storage_key').notNull(),
  sizeBytes: bigint('size_bytes', { mode: 'number' }),
  mimeType: text('mime_type').notNull(),
  ...stamps,
}, (t) => [index('report_assets_report_idx').on(t.reportId)]);

export const comments = rekod.table('comments', {
  id: uuid('id').primaryKey().$defaultFn(() => uuidv7()),
  reportId: uuid('report_id').notNull().references(() => reports.id, { onDelete: 'cascade' }),
  workspaceId: text('workspace_id').notNull().references(() => organization.id, { onDelete: 'cascade' }),
  authorId: text('author_id').references(() => user.id, { onDelete: 'set null' }),
  body: text('body').notNull(),
  timestampMs: integer('timestamp_ms'),
  editedAt: timestamp('edited_at', { withTimezone: true }),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
  ...stamps,
}, (t) => [index('comments_report_created_idx').on(t.reportId, t.createdAt)]);
